# Generated by Django 4.1.2 on 2022-10-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=90, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=90, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='sendermessage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=90, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='sendermessage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=90, max_digits=100, null=True),
        ),
    ]
