# Generated by Django 4.1.2 on 2022-10-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sendermessage_isactive_alter_profile_sendermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sendermessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to='core.sendermessage'),
        ),
    ]
