# Generated by Django 4.1.2 on 2022-10-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hospital_latitude_alter_hospital_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to='core.driver'),
        ),
    ]
