# Generated by Django 4.1.2 on 2022-10-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='driver',
        ),
        migrations.AddField(
            model_name='sendermessage',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_message', to='core.driver'),
        ),
    ]
