# Generated by Django 4.1.2 on 2022-10-15 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_profile_driver_sendermessage_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='drivername',
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendermessage',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
