# Generated by Django 4.1.2 on 2022-10-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_driver_drivername_driver_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendermessage',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='sendermessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to='core.sendermessage'),
        ),
    ]
