# Generated by Django 4.1.2 on 2022-10-15 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sendermessage_driver_driver_sendermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
    ]
